console.log("hello world");
console.error(new Error("error ocured"));
var name="dummy";
console.warn("hey $name");
console.log(__dirname);
console.log(__filename);
console.log(`Process Architecture: ${process.arch}`);  
console.log(`Process PID: ${process.pid}`);  
console.log(`Process Platform: ${process.platform}`);  
console.log(`Process Version: ${process.version}`);  
